# Generated by Django 6.0.6 on 2026-09-11 18:52

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Goal",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "goal_type",
                    models.CharField(
                        choices=[
                            ("outcome", "Outcome Goal"),
                            ("process", "Process Goal"),
                            ("milestone", "Milestone"),
                            ("experience", "Experience"),
                            ("maintenance", "Maintenance / Protection"),
                        ],
                        default="outcome",
                        max_length=16,
                    ),
                ),
                (
                    "baseline",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "target",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                (
                    "target_unit",
                    models.CharField(
                        blank=True,
                        help_text="e.g. $, km, minutes, sessions",
                        max_length=40,
                    ),
                ),
                (
                    "current_value",
                    models.DecimalField(
                        blank=True, decimal_places=2, max_digits=14, null=True
                    ),
                ),
                ("target_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("at_risk", "At Risk"),
                            ("complete", "Complete"),
                            ("paused", "Paused"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=16,
                    ),
                ),
                (
                    "priority",
                    models.PositiveSmallIntegerField(
                        choices=[(1, "High"), (2, "Medium"), (3, "Low")], default=2
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Manual progress, used when there is no numeric baseline/target.",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="goals",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["priority", "target_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="LifeArea",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=120)),
                ("description", models.TextField(blank=True)),
                ("sort_order", models.PositiveIntegerField(default=0)),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Inactive areas are archived, not deleted — history is kept.",
                    ),
                ),
                (
                    "template_key",
                    models.CharField(
                        blank=True,
                        help_text="Which default area this came from, if any.",
                        max_length=32,
                    ),
                ),
                (
                    "north_light",
                    models.TextField(
                        blank=True,
                        help_text="What does “good” ultimately look like in this part of your life?",
                    ),
                ),
                (
                    "why",
                    models.TextField(blank=True, help_text="Why does this matter?"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="life_areas",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["sort_order", "id"],
            },
        ),
        migrations.CreateModel(
            name="Habit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                (
                    "frequency_type",
                    models.CharField(
                        choices=[
                            ("daily", "Daily"),
                            ("weekly", "Weekly"),
                            ("times_per_week", "X times per week"),
                            ("monthly", "Monthly"),
                            ("times_per_month", "X times per month"),
                        ],
                        default="weekly",
                        max_length=20,
                    ),
                ),
                (
                    "frequency_target",
                    models.PositiveSmallIntegerField(
                        default=1,
                        validators=[django.core.validators.MinValueValidator(1)],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "goal",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="habits",
                        to="planning.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "life_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="habits",
                        to="planning.lifearea",
                    ),
                ),
            ],
            options={
                "ordering": ["life_area__sort_order", "title"],
            },
        ),
        migrations.AddField(
            model_name="goal",
            name="life_area",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="planning.lifearea",
            ),
        ),
        migrations.CreateModel(
            name="LifeAreaAssessment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction",
                    models.PositiveSmallIntegerField(
                        help_text="How satisfied am I with this area today? (1–10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        help_text="How important is this area to me? (1–10)",
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ],
                    ),
                ),
                (
                    "strategic_mode",
                    models.CharField(
                        choices=[
                            ("improve", "Improve"),
                            ("protect", "Protect"),
                            ("maintain", "Maintain"),
                            ("explore", "Explore"),
                            ("deemphasize", "De-emphasize"),
                        ],
                        default="maintain",
                        max_length=16,
                    ),
                ),
                (
                    "annual_vision",
                    models.TextField(
                        blank=True,
                        help_text="If this area had genuinely improved by the end of this Personal Year, what would be true?",
                    ),
                ),
                (
                    "assessment_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "life_area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to="planning.lifearea",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="assessments",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["life_area__sort_order", "life_area_id"],
            },
        ),
        migrations.CreateModel(
            name="AssessmentSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "satisfaction",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "importance",
                    models.PositiveSmallIntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(10),
                        ]
                    ),
                ),
                (
                    "strategic_mode",
                    models.CharField(
                        choices=[
                            ("improve", "Improve"),
                            ("protect", "Protect"),
                            ("maintain", "Maintain"),
                            ("explore", "Explore"),
                            ("deemphasize", "De-emphasize"),
                        ],
                        max_length=16,
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        blank=True,
                        help_text="e.g. onboarding, monthly review, annual review",
                        max_length=40,
                    ),
                ),
                ("taken_at", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "assessment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="snapshots",
                        to="planning.lifeareaassessment",
                    ),
                ),
            ],
            options={
                "ordering": ["taken_at"],
            },
        ),
        migrations.CreateModel(
            name="Milestone",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True)),
                (
                    "quarter",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Quarter of the Personal Year, if you think in quarters.",
                        null=True,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(4),
                        ],
                    ),
                ),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("at_risk", "At Risk"),
                            ("complete", "Complete"),
                            ("paused", "Paused"),
                            ("dropped", "Dropped"),
                        ],
                        db_index=True,
                        default="not_started",
                        max_length=16,
                    ),
                ),
                (
                    "progress_percentage",
                    models.PositiveSmallIntegerField(
                        default=0,
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                ("completed_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to="planning.goal",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="milestones",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["due_date", "id"],
            },
        ),
        migrations.CreateModel(
            name="PersonalYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=120)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planning", "Planning"),
                            ("active", "Active"),
                            ("completed", "Completed"),
                            ("archived", "Archived"),
                        ],
                        db_index=True,
                        default="planning",
                        max_length=12,
                    ),
                ),
                (
                    "foundation_start_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional runway before the year starts: baselines, measurements, habit tests, choosing focus.",
                        null=True,
                    ),
                ),
                ("notes", models.TextField(blank=True)),
                (
                    "reflection",
                    models.TextField(
                        blank=True, help_text="Summary written at the end of the year."
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="personal_years",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-start_date"],
            },
        ),
        migrations.AddField(
            model_name="lifeareaassessment",
            name="personal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="assessments",
                to="planning.personalyear",
            ),
        ),
        migrations.AddField(
            model_name="goal",
            name="personal_year",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="goals",
                to="planning.personalyear",
            ),
        ),
        migrations.CreateModel(
            name="Review",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "review_type",
                    models.CharField(
                        choices=[
                            ("monthly", "Monthly Review"),
                            ("quarterly", "Quarterly Review"),
                            ("annual", "Annual Review"),
                            ("life", "Life Review"),
                        ],
                        db_index=True,
                        max_length=12,
                    ),
                ),
                (
                    "review_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                (
                    "period_label",
                    models.CharField(
                        blank=True,
                        help_text="e.g. “September 2027”, “Q3”",
                        max_length=40,
                    ),
                ),
                (
                    "moved_forward",
                    models.TextField(blank=True, verbose_name="What moved forward?"),
                ),
                ("stalled", models.TextField(blank=True, verbose_name="What stalled?")),
                (
                    "surprised",
                    models.TextField(blank=True, verbose_name="What surprised me?"),
                ),
                (
                    "attention_next",
                    models.TextField(
                        blank=True, verbose_name="What deserves attention next?"
                    ),
                ),
                (
                    "no_longer_relevant",
                    models.TextField(
                        blank=True, verbose_name="Are any goals no longer relevant?"
                    ),
                ),
                (
                    "priorities_changed",
                    models.TextField(
                        blank=True, verbose_name="Have my priorities changed?"
                    ),
                ),
                (
                    "north_light_check",
                    models.TextField(
                        blank=True,
                        verbose_name="Does the North Light still feel correct? Is this still what I want?",
                    ),
                ),
                ("lessons", models.TextField(blank=True, verbose_name="Lessons")),
                (
                    "major_events",
                    models.TextField(blank=True, verbose_name="Major events"),
                ),
                (
                    "carry_forward",
                    models.TextField(blank=True, verbose_name="What carries forward?"),
                ),
                ("notes", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "personal_year",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="planning.personalyear",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-review_date", "-id"],
            },
        ),
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("display_name", models.CharField(blank=True, max_length=120)),
                ("timezone", models.CharField(default="UTC", max_length=64)),
                (
                    "year_start_type",
                    models.CharField(
                        choices=[
                            ("calendar", "Calendar year (January 1)"),
                            ("birthday", "Birthday to birthday"),
                            ("custom", "Custom annual start date"),
                        ],
                        default="calendar",
                        max_length=16,
                    ),
                ),
                (
                    "birthday",
                    models.DateField(
                        blank=True,
                        help_text="Only needed for birthday-based years or a birthday Life Review.",
                        null=True,
                    ),
                ),
                (
                    "custom_year_start",
                    models.DateField(
                        blank=True,
                        help_text="Month and day are used; the year is ignored.",
                        null=True,
                    ),
                ),
                (
                    "life_review_date",
                    models.DateField(
                        blank=True,
                        help_text="Optional annual deep Life Review date (e.g. your birthday), separate from Personal Year planning.",
                        null=True,
                    ),
                ),
                (
                    "review_cadence",
                    models.CharField(
                        choices=[("monthly", "Monthly"), ("quarterly", "Quarterly")],
                        default="monthly",
                        max_length=16,
                    ),
                ),
                (
                    "reminders_enabled",
                    models.BooleanField(
                        default=False,
                        help_text="Architecture placeholder — no reminders are sent in V1.",
                    ),
                ),
                ("onboarding_step", models.PositiveSmallIntegerField(default=1)),
                ("onboarding_complete", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="GoalRelationship",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "outcome_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supporting_links",
                        to="planning.goal",
                    ),
                ),
                (
                    "process_goal",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supports_links",
                        to="planning.goal",
                    ),
                ),
            ],
            options={
                "constraints": [
                    models.UniqueConstraint(
                        fields=("outcome_goal", "process_goal"), name="unique_goal_link"
                    ),
                    models.CheckConstraint(
                        condition=models.Q(
                            ("outcome_goal", models.F("process_goal")), _negated=True
                        ),
                        name="goal_cannot_support_itself",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="HabitCheckin",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(default=django.utils.timezone.localdate)),
                ("count", models.PositiveSmallIntegerField(default=1)),
                (
                    "habit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="checkins",
                        to="planning.habit",
                    ),
                ),
            ],
            options={
                "ordering": ["-date"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("habit", "date"), name="one_checkin_per_habit_per_day"
                    )
                ],
            },
        ),
        migrations.AddIndex(
            model_name="lifearea",
            index=models.Index(
                fields=["user", "is_active", "sort_order"],
                name="planning_li_user_id_fa3f7f_idx",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalyear",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gt", models.F("start_date"))),
                name="personal_year_end_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="personalyear",
            constraint=models.UniqueConstraint(
                condition=models.Q(("status", "active")),
                fields=("user",),
                name="one_active_personal_year_per_user",
            ),
        ),
        migrations.AddConstraint(
            model_name="lifeareaassessment",
            constraint=models.UniqueConstraint(
                fields=("personal_year", "life_area"),
                name="one_assessment_per_area_per_year",
            ),
        ),
        migrations.AddIndex(
            model_name="goal",
            index=models.Index(
                fields=["user", "personal_year", "status"],
                name="planning_go_user_id_622e5a_idx",
            ),
        ),
    ]
